### ISSUE TITLE
minor error in support Scroll Fodder fusion table

### ISSUE THREAD

**Issue by Diclah** [Zekareisoujin/MFFFusionCalc#3]
Tested on Taunt

- Card type   **Support** 
- Special options **none**
- Minimum card fusion chance **100**
- Minimum fodder fusion chance **100**
- Minimum fodder level **2**

Fodder fusion table

Fusion	|Method	Cost	|Cummulative cost
-|-|-
2 → 3	| 2 × AL2 (50% each);|	2 × AL2 cards	2 × AL2 cards
3 → 4	|**_1 × AL2 (33% each);_** 1 × AL3 (80% each);|	4 × AL2 cards	6 × AL2 cards

**_1 × AL2 (33% each);_** should be **_1 × AL2 (30% each);_**

**Comment by Zekareisoujin** [comment]
Verified & update the fusion rate table.
